### ISSUE TITLE
Find Intelligent Starting Point

### ISSUE THREAD

**Issue by samirahmed** [Algorithmix/Papyrus#7]
Currently this is hard coded [here](https://github.com/Algorithmix/Papyrus/blob/master/Papyrus/Algorithmix/Preprocessing/Preprocessing.cs#L352-L355)

**Comment by crowell** [comment]
fixed : bef66415a9177f6d1eb0648549491ee92c807fda
uses a constant of 5 for the color difference, that can be tweaked, but the concept is there
